###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
networks:
  laravel11:
    name: larvel11
services:
    # laravel11 .env 的 REDIS_HOST=redis
    redis:
        image: 'redis:alpine'
        container_name: redis
        networks:
            - laravel11

    # laravel11 .env 的 DB_HOST=mysql, DB_PORT=3306 因為這是走內網
    mysql:
        image: 'mysql:8.0'
        container_name: mysql
        restart: unless-stopped
        # working_dir: /application
        volumes:
            - ./phpdocker/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=poc
            - MYSQL_PASSWORD=root
        ports:
            - '33060:3306'
        networks:
            - laravel11
    webserver:
        build: phpdocker/nginx
        # working_dir: /application
        container_name: nginx
        volumes:
            - '.:/var/www/html'
            - './phpdocker/nginx/nginx_main.conf:/etc/nginx/conf.d/default.conf'
            - './phpdocker/nginx:/etc/nginx/conf.d'
            - './phpdocker/nginx/fastcgi_params:/etc/nginx/fastcgi_params'
            - './phpdocker/nginx/_wildcard.jp.ngrok.io+3-key.pem:/etc/nginx/_wildcard.jp.ngrok.io+3-key.pem'
            - './phpdocker/nginx/_wildcard.jp.ngrok.io+3.pem:/etc/nginx/_wildcard.jp.ngrok.io+3.pem'
        ports:
            - '8888:80'
            - '443:443'
        depends_on:
            - php-fpm-82
            - mysql
        networks:
            - laravel11
    php-fpm-82:
        build: phpdocker/php-fpm-82
        working_dir: /var/www/html
        container_name: php82
        volumes:
            - '.:/var/www/html'
            - ./phpdocker/php-fpm-82/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./phpdocker/php-fpm-82/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        extra_hosts:
            # "<要連線的 local>:host-gateway"
            - "ting-php8.jp.ngrok.io:192.168.65.2"
        networks:
            - laravel11


